from elasticsearch import Elasticsearch
import ssl

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "WYK3jpc56t7Wq8lQfcz9K53l"

# Found in the 'Manage Deployment' page
CLOUD_ID = "My_deployment:YXAtc291dGgtMS5hd3MuZWxhc3RpYy1jbG91ZC5jb206NDQzJGU5NDEzMDNkODA5ZDQyOTA4Mjk0NmMwMWJmMTAxMmM4JGU5NDc2ZGNmYWI0ZDQzZjlhOTBmZTE0NTA1NzJjZDYx"

# Create the client instance
es = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD),
    verify_certs=False,
    ssl_version=ssl.TLSVersion.TLSv1_2
)

# Successful response!
# print(es.info())

query = "sort"
key_fields = [ "name", "description", "keywords", "tags", "presentableFormat" ] 
max_size = 10

es_query = {"query": {
    "multi_match" : {
      "query":    query,
      "fields": key_fields
    }
}}

resp = es.search(index="code_snippets", body={
    "size": max_size,
    "query": es_query["query"]
})

#print(f"Response: {resp}")

print("Got %d Hits:" % resp['hits']['total']['value'])
for hit in resp['hits']['hits']:
    print(f"{hit['_source']}")


